trigger:
- master
- develop

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: BuildFrontend
    steps:
      - task: UseNode@1
        inputs:
          checkLatest: true
        displayName: 'Install Node.js'
      - script: |
          npm install
        displayName: 'npm install'
      - script: |
          npm run prod
        displayName: 'npm run prod'
  - job: BuildBackend
    steps:
      - task: DotNetCoreCLI@2
        inputs:
          command: 'restore'
          projects: '**/*.csproj'
        displayName: 'dotnet restore'
      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'
          projects: '**/*.csproj'
        displayName: 'dotnet build'

- stage: Test
  jobs:
  - job: RunBackendUnitTests
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: test
        projects: '**/test/**/*.csproj'